# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adam DJ Brett
description: "I am a Ph.D. Candidate in the Religion Department at Syracuse University where I study American Religion."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://dev.theological.me" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: swiss # the GitHub repo name for your project
github_username: adamdjbrett
remote_theme: broccolini/swiss

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: adjbx

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: red

# Customizations
logo: 'assets/img/logo.png'
locale: en_US

# Build settings
markdown: kramdown

include:
  - _pages

exclude:
  - CHANGELOG.MD
  - CNAME
  - LICENSE.txt
  - README.md
