# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adam DJ Brett
description: "I am a Ph.D. Candidate in the Religion Department at Syracuse University where I study American Religion."
baseurl:  # the subpath of your site, e.g. /blog
url: "https://www.adamdjbrett.com" # the base hostname & protocol for your site, e.g. http://example.com
production_url: 'https://www.adamdjbrett.com'
github_repo: adamdjbrett.github.io # the GitHub repo name for your project
github_username: adamdjbrett
repository: adamdjbrett/adamdjbrett.github.io.

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: __adjb

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: red

# Customizations
logo: 'assets/img/logo.png'
locale: en-US

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  excerpt_separator: "<!--more-->"

# Permalinks
permalink: /:title/

# Plugins
plugins:
  -  jekyll-gist
  -  jekyll-paginate
  -  jekyll-seo-tag
  -  jekyll-sitemap
  -  jekyll-include-cache
  -  jekyll-redirect-from

sass:
    sass_dir: _sass
    sourcemap: true

include:
  - _pages
  - _redirects

exclude:
  - CHANGELOG.MD
  - CNAME
  - LICENSE.txt
  - README.md
